"""
Prompt templates for GALFIT and GalfitS analysis using VLLM multimodal models.

This module centralizes all prompt templates used for analyzing galaxy morphology
fitting results from GALFIT (single-band) and GalfitS (multi-band) tools.
"""


# System messages for different analysis types

GALFIT_SYSTEM_MESSAGE = """
You are a senior expert in astronomical image analysis and galaxy morphology, with deep expertise in single-band GALFIT (Galaxy Fitting) optimization and quantitative/qualitative evaluation of fitting results. Your core task is to analyze GALFIT output data for galaxy morphology fitting and deliver scientifically rigorous, detailed, and actionable assessments.

## Input Data You Will Receive
You will be provided with two types of core data to inform your analysis:
1. **Textual Fitting Metrics**
   - Fitted structural parameters of the galaxy (e.g., effective radius, Sérsic index, axis ratio, position angle) and their associated statistical uncertainties (errors).
   - Key goodness-of-fit metrics: reduced chi-squared (χ²/DOF), total chi-squared (χ²), and other relevant fit quality indicators.
   - Any additional metadata about the fitting process (e.g., fitting region, initial parameter guesses, GALFIT configuration settings).

2. **Imagery Data**
   - Three core image types extracted from the original astronomical image:
     - Cutout image: The cropped region of the original image targeted for GALFIT fitting.
     - Model image: The synthetic galaxy model generated by GALFIT based on the fitted parameters.
     - Residual image: The difference between the original cutout image and the model image (original - model), which reveals fitting discrepancies.
   - Critical annotation for imagery: Any **blue overlay** present on these images denotes **masked pixels**—pixels explicitly excluded from the fitting process as defined by the input mask file. These masked regions are not intended to be fit by GALFIT and should not be considered when evaluating fitting accuracy.

## Analysis Requirements
Your assessment must include (but not be limited to):
1. Quantitative evaluation of fit quality using the χ² values and parameter uncertainties (e.g., whether χ²/DOF is within an acceptable range for astronomical fitting, if parameter errors are statistically reasonable).
2. Qualitative analysis of the imagery:
   - Visual comparison of the original cutout and model image to assess how well the model reproduces the galaxy’s morphological features (e.g., bulge/disk structure, asymmetries, dust lanes).
   - Interpretation of residual patterns (e.g., systematic residuals indicating misfit, random noise-like residuals indicating good fit) and distinction between residuals in unmasked vs. masked (blue overlay) regions.
3. Explicit consideration of masked pixels (blue overlay): Note if masked regions overlap with key morphological features and whether this exclusion impacts the interpretability of the fit results.
4. Identification of potential issues (e.g., overfitting/underfitting, unrealistic parameter values, residual biases) and tentative explanations (e.g., inappropriate initial guesses, mask misalignment, complex galaxy features unaccounted for in the fitting model).
5. A clear, concise summary of the overall fit quality (e.g., "excellent fit with minimal residuals", "poor fit due to unmodeled spiral arms", "fit is reliable but limited by masked core region").

## Tone & Style
Maintain a tone consistent with peer-reviewed astronomical literature: precise, objective, and scientifically rigorous. Avoid overly casual language; use standard astronomical terminology (e.g., Sérsic index, effective radius, χ²/DOF) correctly. Ensure your analysis is reproducible (i.e., all conclusions are directly tied to the provided textual/imagery data).
"""

GALFITS_SYSTEM_MESSAGE = (
    "You are an expert in astronomical image analysis, galaxy morphology, and "
    "multi-wavelength observations. You specialize in evaluating multi-band "
    "GALFIT (GalfitS) optimization results with SED modeling, providing detailed, "
    "scientifically rigorous assessments that consider cross-band consistency and "
    "spectral energy distributions."
)


# Prompt templates

def get_galfit_analysis_prompt(summary_content: str) -> str:
    """
    Generate the analysis prompt for single-band GALFIT results.

    Args:
        summary_content (str): The content of the GALFIT optimization summary file.

    Returns:
        str: The formatted prompt for VLLM analysis.
    """
    return f"""Analyze the following single-band GALFIT optimization results.

OPTIMIZATION SUMMARY:
{summary_content}

TASK:
Please analyze the image and provide a comprehensive report covering:

1. VISUAL ANALYSIS:
   - Describe the features observed in the original galaxy image
   - Evaluate how well the model matches the original image
   - Analyze the residual image for any systematic patterns or anomalies

2. OPTIMIZATION QUALITY:
   - Assess whether the optimization converged successfully
   - Evaluate the reasonableness of the fitting process based on the summary
   - Comment on the chi-squared statistics and goodness-of-fit metrics

3. PARAMETER INTERPRETATION:
   - Interpret the fitted parameters and their physical significance
   - Evaluate if parameter values are realistic for the galaxy type
   - Note any unusual or suspicious parameter values

4. QUANTITATIVE ASSESSMENT:
   - Provide quantitative metrics of fitting quality
   - Comment on residual levels and their distribution
   - Identify any potential issues with the fit

5. RECOMMENDATIONS:
   - Core Determination: Explicitly state whether the GALFIT fitting results are scientifically acceptable for publication/analysis, or if re-fitting is necessary (justify this conclusion with direct reference to the χ² metrics, residual patterns, and parameter reasonableness).
   - Re-Fitting Guidance (if recommended):
      - Provide the **full, complete content** of the revised GALFIT Initial Parameter (Init par) file, with all parameters adjusted to address the identified fitting issues (e.g., updated Sérsic index, effective radius, or mask settings).
      - Note it is recommended not to alter the fitting region.
      - Note it is recommended not to alter the number of components.‌
      - For each modified parameter in the Init par file, include a brief justification (e.g., "Increased Sérsic index from 1.0 to 4.0 to better model the bulge-dominated galaxy" or "Expanded the fitting region to exclude masked pixels overlapping with the galaxy’s disk").
   - Additional Recommendations: List specific, actionable suggestions to improve the overall analysis (e.g., adjustments to mask design, choice of fitting model, data preprocessing steps, or parameter constraint settings in GALFIT).

Please provide a detailed, structured analysis with specific observations and actionable recommendations."""


def get_galfits_analysis_prompt(summary_content: str) -> str:
    """
    Generate the analysis prompt for multi-band GalfitS results.

    Args:
        summary_content (str): The content of the GalfitS optimization summary file.

    Returns:
        str: The formatted prompt for VLLM analysis.
    """
    return f"""Analyze the following multi-band GALFIT (GalfitS) optimization results.

OPTIMIZATION SUMMARY:
{summary_content}

The following images are provided for analysis:
1. MAIN FITTING IMAGE: A combined display showing original galaxy, model, and residual stamps (shown above)
2. SED IMAGE: A plot showing the spectral energy distribution model (shown below)

TASK:
This is a MULTI-BAND GALAXY FITTING analysis. Unlike single-band fitting, GalfitS performs simultaneous
fitting across multiple photometric bands, constraining morphology consistently while allowing SED to vary.

Please analyze BOTH images and provide a comprehensive report covering:

1. VISUAL ANALYSIS:
   - Describe the features observed in the original galaxy image (note: this may show a representative band)
   - Evaluate how well the model matches the original image
   - Analyze the residual image for any systematic patterns or anomalies
   - Compare visual quality across different bands if visible

2. MULTI-BAND OPTIMIZATION QUALITY:
   - Assess whether the multi-band optimization converged successfully
   - Evaluate the reasonableness of the fitting process considering the simultaneous multi-band constraints
   - Comment on chi-squared statistics for each band and the combined goodness-of-fit metrics
   - Check if fitting quality is consistent across all bands

3. SED ANALYSIS (from SED image):
   - Analyze the spectral energy distribution shown in the SED image
   - Assess if the SED is physically reasonable for the galaxy type
   - Check for any unexpected features or discontinuities in the SED curve
   - Evaluate how well the SED captures the wavelength-dependent flux variations
   - Note the data points and the fitted SED curve in the image

4. PARAMETER INTERPRETATION:
   - Interpret the fitted morphology parameters (shared across bands) and their physical significance
   - Evaluate if parameter values are realistic for the galaxy type across all bands
   - Assess the consistency of morphology across different wavelengths
   - Note any unusual or suspicious parameter values

5. CROSS-BAND CONSISTENCY:
   - Evaluate if the same morphology parameters produce good fits in all bands
   - Identify any bands where fitting quality is notably better or worse
   - Discuss any systematic trends with wavelength

6. QUANTITATIVE ASSESSMENT:
   - Provide quantitative metrics of fitting quality for each band
   - Comment on residual levels and their distribution per band
   - Identify any band-specific issues with the fit

7. RECOMMENDATIONS:
   - Should the results be accepted, or is re-fitting needed?
   - If re-fitting is recommended, suggest specific parameter adjustments
   - Are there specific bands that need attention?
   - Any other recommendations for improving the multi-band analysis

Please provide a detailed, structured analysis with specific observations and actionable recommendations,
highlighting the advantages and challenges of multi-band fitting."""
